### ISSUE TITLE
number of channels error

### ISSUE THREAD

**Issue by nmddc0211** [vincrichard/EfficientPS#1]
Hi @vincrichard,
thank you for your word. I currently have an issue that I can't solve. I would appreciate it if you could help me with it.

 Traceback (most recent call last):
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/train_net.py", line 164, in <module>
    main()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/train_net.py", line 161, in main
    trainer.fit(efficientps, train_loader, val_dataloaders=valid_loader)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/efficientps/model.py", line 131, in optimizer_step
    optimizer.step(closure=closure)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 85, in optimizer_step
    closure_result = closure()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 213, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/efficientps/model.py", line 41, in training_step
    _, loss = self.shared_step(batch)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/efficientps/model.py", line 52, in shared_step
    pyramid_features = self.fpn(features)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/efficientps/fpn/two_way_fpn.py", line 155, in forward
    b_up_x32 = self.conv_b_up_x32(b_up_x32)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/dangnguyen/myProjects/EfficientPS_vinc/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [256, 2048, 1, 1], expected input[3, 512, 16, 32] to have 2048 channels, but got 512 channels instead
Epoch 0:   0%|          | 0/1159 [00:05<?, ?it/s]

**Comment by vincrichard** [comment]
Hello, sorry to hear you are having trouble with the code. Did you make any change in the config ? It has been a while since I run the code so it will help if you can provide me with all the changes you may or may not have done.

**Comment by nmddc0211** [comment]
Hi, I didn't make any change in the config file other than rewrite the dataset path. 
I also prepared the dataset by running cityscapesScripts to get the panoptic annotations.

**Comment by vincrichard** [comment]
Could you check the size of the `reduction_5` output being of the backbone (given by `features = self.backbone.extract_endpoints(inputs['image'])`).

I check on my end and I get the right number of layer so I don't really know what is happening on your end

**Comment by nmddc0211** [comment]
Thanks for the help!
I printed all the tensor sizes and here is what I got:

reduction_1: torch.Size([3, 24, 256, 512])
reduction_2: torch.Size([3, 40, 128, 256])
reduction_3: torch.Size([3, 64, 64, 128])
reduction_4: torch.Size([3, 176, 32, 64])
reduction_5: torch.Size([3, 512, 16, 32])
reduction_6: torch.Size([3, 2048, 16, 32])

**Comment by nmddc0211** [comment]
Hi there,
I change reduction_5 to reduction_6 in two_way_fpn.py and it seems to work! Maybe the problem has something to do with efficientNet_pytorch.

**Comment by vincrichard** [comment]
Okay you should change the "reduction_5" to "reduction_6" [here](https://github.com/vincrichard/EfficientPS/blob/e8d0548a05f816293a0adb596ec177f174335010/efficientps/fpn/two_way_fpn.py#L153)

This should solve the error you are getting. I am not really sure why you get the error in the first place. Maybe the dependencie of EfficentNet Pytorch
