### ISSUE TITLE
TypeError: optimizer_step() missing 1 required positional argument: 'closure'

### ISSUE THREAD

**Issue by aakutka** [vincrichard/EfficientPS#7]
Hi I have looked everywhere and done everything that made sense to me to get rid of this error and nothing seems to work. It would be a huge help if you could help me out with this. 

I am working with:
pytorch = 1.13.1
Cuda = 11.7
python = 3.9.13

The error:

Traceback (most recent call last):
  File "C:\Users\singh\Downloads\EfficientPS\impl\EfficientPS\train_net.py", line 178, in <module>
    main()
  File "C:\Users\singh\Downloads\EfficientPS\impl\EfficientPS\train_net.py", line 175, in main
    trainer.fit(efficientps, train_loader, val_dataloaders=valid_loader)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 521, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 560, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 936, in _run
    results = self._run_stage()
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 979, in _run_stage
    self.fit_loop.run()
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 201, in run
    self.advance()
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\optimization\automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\loops\optimization\automatic.py", line 261, in _optimizer_step
    call._call_lightning_module_hook(
  File "C:\Users\singh\anaconda3\envs\efficientPS_env\lib\site-packages\pytorch_lightning\trainer\call.py", line 143, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
**TypeError: optimizer_step() missing 1 required positional argument: 'closure'**
Epoch 0:   0%|          | 0/992 [00:19<?, ?it/s]

**Comment by vincrichard** [comment]
Hello,
It is probably because of the pytorch lighting version, but I did not fix the version in the `requirement.txt` at the time. It's probably because pytorch lightning was updated to 2.0 recently. Try using an older version. 
Sorry for the trouble, the environment should have been better maintained at the time. Right now I don't have any way to know the proper version used.

**Comment by aakutka** [comment]
Hi,
I changed the version and works perfectly now!!
Thank you for the quick response. The version that worked for me was 1.5.8.
